{% set name = "opentelemetry-instrumentation-grpc" %}
{% set version = "0.36b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_grpc-{{ version }}.tar.gz
  sha256: dc89447c9eb6ea868970f6c13b4ffdac182cdd5a41dd215a0f5393ca6375be55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.36b0
    - opentelemetry-sdk >=1.12,<2.dev0
    - opentelemetry-semantic-conventions ==0.36b0
    - wrapt <2.0.0,>=1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc
  summary: OpenTelemetry gRPC instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
