{% set name = "opentelemetry-instrumentation-grpc" %}
{% set version = "0.24b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-grpc-{{ version }}.tar.gz
  sha256: ca5219a95630c332a6bf202144f7dfb59fa45bf9e560a152e7de8ff6408b3f3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - opentelemetry-sdk ~=1.3
    - opentelemetry-semantic-conventions ==0.24b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    - protobuf >=3.13.0
    # - opentelemetry-test ==0.24b0
    - grpcio ~=1.27

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc
  summary: OpenTelemetry gRPC instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
